# Generated by Django 5.2.9 on 2026-04-28 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_templates(apps, schema_editor):
    Template = apps.get_model('ai_starter', 'Template')
    templates = [
        (
            'local_service',
            'Local Service',
            [
                {'key': 'hero', 'type': 'hero_lr'},
                {'key': 'services', 'type': 'list'},
                {'key': 'contact', 'type': 'contact_form'},
                {'key': 'cta', 'type': 'cta'},
            ],
        ),
        (
            'growth_offer',
            'Growth Offer',
            [
                {'key': 'hero', 'type': 'hero_lr'},
                {'key': 'benefits', 'type': 'benefits'},
                {'key': 'services', 'type': 'list'},
                {'key': 'cta', 'type': 'cta'},
                {'key': 'contact', 'type': 'contact_form'},
            ],
        ),
        (
            'starter_onepage',
            'Starter Onepage',
            [
                {'key': 'hero', 'type': 'hero_simple'},
                {'key': 'contact', 'type': 'contact_form'},
                {'key': 'cta', 'type': 'cta'},
            ],
        ),
    ]

    for slug, name, layout in templates:
        Template.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'layout_json': layout,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ai_starter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('layout_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_slug', models.SlugField(default='local_service', max_length=80)),
                ('business_name', models.CharField(max_length=120)),
                ('service_type', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=80)),
                ('field_key', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ai_starter.site')),
            ],
            options={
                'ordering': ['section_key', 'field_key', 'language'],
                'constraints': [models.UniqueConstraint(fields=('site', 'section_key', 'field_key', 'language'), name='unique_site_content_field_per_language')],
            },
        ),
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
