# Generated by Django 5.2.9 on 2026-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_starter', '0002_template_site_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='color_palette',
            field=models.CharField(choices=[('orange_black', 'Orange / Black'), ('blue_dark', 'Blue / Dark'), ('green_neutral', 'Green / Neutral'), ('red_charcoal', 'Red / Charcoal')], default='orange_black', max_length=40),
        ),
    ]
