# Generated by Django 5.2.9 on 2026-05-29 00:00

import ai_starter.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_starter', '0003_site_color_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storage_key', models.CharField(default=ai_starter.models.build_request_storage_key, editable=False, max_length=40, unique=True)),
                ('source_code', models.CharField(default='GEMEENTE50', max_length=40)),
                ('normal_price', models.DecimalField(decimal_places=2, default=325, max_digits=8)),
                ('offer_price', models.DecimalField(decimal_places=2, default=275, max_digits=8)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('reviewed', 'Reviewed')], default='new', max_length=20)),
                ('business_name', models.CharField(max_length=120)),
                ('business_type', models.CharField(max_length=120)),
                ('existing_website_url', models.URLField(blank=True)),
                ('current_domain', models.CharField(blank=True, max_length=255)),
                ('needs_domain_help', models.BooleanField(default=False)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('service_area', models.CharField(blank=True, max_length=255)),
                ('main_language', models.CharField(max_length=12)),
                ('extra_languages', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=40)),
                ('main_services', models.TextField()),
                ('business_description', models.TextField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('social_links', models.TextField(blank=True)),
                ('preferred_colors', models.CharField(blank=True, max_length=255)),
                ('style_notes', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=ai_starter.models.PrivateUploadStorage(), upload_to=ai_starter.models.request_file_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website_request', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='files', to='ai_starter.websiterequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
