# Generated by Django 5.2.9 on 2026-06-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_starter', '0004_websiterequest_websiterequestfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('sent', 'Sent'), ('applied', 'Applied'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('target_system', models.CharField(default='wordpress_jcw', max_length=40)),
                ('wordpress_site_url', models.URLField(blank=True)),
                ('wordpress_admin_url', models.URLField(blank=True)),
                ('wordpress_user_reference', models.CharField(blank=True, max_length=255)),
                ('handoff_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_site_handoffs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='ai_starter.site')),
                ('website_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to='ai_starter.websiterequest')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
