# Generated by Django 5.2.9 on 2026-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_starter', '0005_sitehandoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitehandoff',
            name='staff_ai_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitehandoff',
            name='staff_ai_brief_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitehandoff',
            name='staff_ai_brief_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
