# Generated by Django 5.2.9 on 2026-06-29 17:27

from django.db import migrations, models


def seed_service_options(apps, schema_editor):
    ServiceOption = apps.get_model('core', 'ServiceOption')
    rows = [
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'starter_catalog',
            'language': 'en',
            'eyebrow': 'Starter Catalog',
            'title': 'Starter Catalog / WhatsApp Orders',
            'price_label': 'From €149 + VAT',
            'summary': 'Best for small resellers, Avon-style sellers, menus, stock lists, parts, and simple product ranges. Visitors browse products and order through WhatsApp, phone, or a contact form.',
            'good_for': 'Small resellers\nAvon-style sellers\nMenus\nStock lists\nParts\nSimple product ranges',
            'includes': 'Product list or catalog pages\nProduct images and details\nCategories if needed\nWhatsApp/contact order button\nNo full checkout required\nCan grow into a shop later',
            'cta_label': 'Ask about a catalog',
            'cta_url': '/en/contact/',
            'sort_order': 10,
            'is_active': True,
        },
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'full_ecommerce',
            'language': 'en',
            'eyebrow': 'Full eCommerce',
            'title': 'Full eCommerce Shop',
            'price_label': 'From €595 + VAT',
            'summary': 'Best for businesses that want customers to buy online with cart, checkout, and payment setup guidance through WooCommerce.',
            'good_for': 'Businesses ready to sell online with checkout',
            'includes': 'WooCommerce setup\nProduct pages and categories\nCart and checkout\nPayment setup guidance\nShipping and tax/VAT structure\nShop dashboard',
            'cta_label': 'Ask about an online shop',
            'cta_url': '/en/contact/',
            'sort_order': 20,
            'is_active': True,
        },
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'reseller_ecommerce',
            'language': 'en',
            'eyebrow': 'Reseller eCommerce',
            'title': 'eCommerce for Resellers',
            'price_label': 'From €1,250 + VAT',
            'summary': 'Best for larger catalogs, specialist product ranges, trade products, vehicle parts, or reseller-style businesses that need more structure than a basic shop.',
            'good_for': 'Larger catalogs\nTrade products\nVehicle/parts businesses',
            'includes': 'Larger catalog structure\nProduct categories and filters\nQuote/order enquiry flow\nReseller-style product presentation\nCustom setup planning\nPossible upgrade to checkout/payment flow',
            'cta_label': 'Discuss reseller eCommerce',
            'cta_url': '/en/contact/',
            'sort_order': 30,
            'is_active': True,
        },
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'starter_catalog',
            'language': 'nl',
            'eyebrow': 'Starter Catalog',
            'title': 'Starter Catalog / WhatsApp Orders',
            'price_label': 'Vanaf €149 + btw',
            'summary': 'Geschikt voor kleine resellers, Avon-achtige verkopers, menu’s, voorraadoverzichten, onderdelen en eenvoudige productreeksen. Bezoekers bekijken producten en bestellen via WhatsApp, telefoon of een contactformulier.',
            'good_for': 'Kleine resellers\nAvon-achtige verkopers\nMenu’s\nVoorraadoverzichten\nOnderdelen\nEenvoudige productreeksen',
            'includes': 'Productlijst of cataloguspagina’s\nProductafbeeldingen en details\nCategorieën indien nodig\nWhatsApp/contactknop voor bestellingen\nGeen volledige checkout nodig\nKan later doorgroeien naar een shop',
            'cta_label': 'Vraag naar een catalogus',
            'cta_url': '/nl/contact/',
            'sort_order': 10,
            'is_active': True,
        },
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'full_ecommerce',
            'language': 'nl',
            'eyebrow': 'Full eCommerce',
            'title': 'Full eCommerce Shop',
            'price_label': 'Vanaf €595 + btw',
            'summary': 'Geschikt voor bedrijven die online willen verkopen met winkelwagen, checkout en begeleiding bij de betaalopzet via WooCommerce.',
            'good_for': 'Bedrijven die online willen verkopen met checkout',
            'includes': 'WooCommerce-setup\nProductpagina’s en categorieën\nWinkelwagen en checkout\nBegeleiding bij de betaalopzet\nVerzend- en btw-structuur\nShopdashboard',
            'cta_label': 'Vraag naar een webshop',
            'cta_url': '/nl/contact/',
            'sort_order': 20,
            'is_active': True,
        },
        {
            'section_key': 'catalog_ecommerce',
            'option_key': 'reseller_ecommerce',
            'language': 'nl',
            'eyebrow': 'Reseller eCommerce',
            'title': 'eCommerce for Resellers',
            'price_label': 'Vanaf €1.250 + btw',
            'summary': 'Geschikt voor grotere catalogi, specialistische productreeksen, handelsproducten, voertuigonderdelen of reseller-achtige bedrijven die meer structuur nodig hebben dan een basiswebshop.',
            'good_for': 'Grotere catalogi\nHandelsproducten\nVoertuig-/onderdelenbedrijven',
            'includes': 'Grotere catalogusstructuur\nProductcategorieën en filters\nOfferte-/bestelaanvraagflow\nReseller-achtige productpresentatie\nPlanning van maatwerkopzet\nMogelijke uitbreiding naar checkout/betalingen',
            'cta_label': 'Bespreek reseller eCommerce',
            'cta_url': '/nl/contact/',
            'sort_order': 30,
            'is_active': True,
        },
    ]

    for row in rows:
        ServiceOption.objects.update_or_create(
            section_key=row['section_key'],
            option_key=row['option_key'],
            language=row['language'],
            defaults=row,
        )


def unseed_service_options(apps, schema_editor):
    ServiceOption = apps.get_model('core', 'ServiceOption')
    ServiceOption.objects.filter(section_key='catalog_ecommerce').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('catalog_ecommerce', 'Catalog / eCommerce')], default='catalog_ecommerce', max_length=64)),
                ('option_key', models.CharField(choices=[('starter_catalog', 'Starter catalog'), ('full_ecommerce', 'Full eCommerce'), ('reseller_ecommerce', 'Reseller eCommerce')], max_length=64)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=8)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('price_label', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField()),
                ('good_for', models.TextField(blank=True)),
                ('includes', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section_key', 'language', 'sort_order', 'id'],
                'unique_together': {('section_key', 'option_key', 'language')},
            },
        ),
        migrations.RunPython(seed_service_options, unseed_service_options),
    ]
