from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/domain-information/', views.dashboard_domain_information, name='dashboard_domain_information'),
    path('how-it-works/', views.how_it_works, name='how_it_works'),
    path('templates/', views.examples, name='templates'),
    path('examples/', views.examples, name='examples'),
    path('plans/', views.plans, name='plans'),
    path('pricing/', views.plans, name='pricing'),
    path('websites/', views.websites, name='websites'),
    path('ads/', views.ads, name='ads'),
    path('online-shop/', views.online_shop, name='online_shop'),
    path('payment-methods/', views.payment_methods, name='payment_methods'),
    path('catalog-and-ecommerce/', views.catalog_and_ecommerce, name='catalog_and_ecommerce'),
    path('catalogus-en-webshop/', views.catalog_and_ecommerce, name='catalog_and_ecommerce_nl'),
    path('facebook-posts/', views.facebook_posts, name='facebook_posts'),
    path('facebook-instagram-ads/', views.facebook_instagram_ads, name='facebook_instagram_ads'),
    path('google-ads/', views.google_ads, name='google_ads'),
    path('linkedin-ads/', views.linkedin_ads, name='linkedin_ads'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),
    path('assistant/help/', views.assistant_help, name='assistant_help'),
    path('staff/assistant-proof/', views.assistant_proof, name='assistant_proof'),
    path('payment/', views.website_package_payment, name='payment'),
    path('after-payment/', views.after_payment, name='after_payment'),
    path('support/', views.support, name='support'),
    path('pay/website-package/', views.website_package_payment, name='website_package_payment'),
    path('activate/website-package/', views.website_package_payment, name='website_package_activation'),
    path('activate/hmd-klusbedrijf/', views.hmd_activation, name='hmd_activation'),
    path('activate/hmd-klusbedrijf/thank-you/', views.hmd_activation_thank_you, name='hmd_activation_thank_you'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy_legacy'),
    path('cookies/', views.cookie_policy, name='cookie_policy'),
    path('what-is-included/', views.what_is_included, name='what_is_included'),
    path('payment-and-cancellation/', views.payment_and_cancellation, name='payment_and_cancellation'),
    path('domain-hosting-and-dashboard/', views.domain_hosting_and_dashboard, name='domain_hosting_and_dashboard'),
    path('add-ons-and-upgrades/', views.addons_and_upgrades, name='addons_and_upgrades'),
    path('preview-licence/', views.preview_licence, name='preview_licence'),
    path('preview-license/', views.preview_licence, name='preview_license_legacy'),
    path('plans/one-time-website/', views.one_time_website_plan, name='one_time_website_plan'),
    path('plans/monthly-website/', views.monthly_plan, name='monthly_plan'),
    path('plans/monthly-plan/', views.monthly_plan, name='monthly_plan_legacy'),
    path('plans/ecommerce-plan/', views.ecommerce_plan, name='ecommerce_plan'),
    path('ai-website/', views.ai_website, name='ai_website'),
    path('business-website/', views.business_website, name='business_website'),
    path('managed/', views.managed, name='managed'),
]
