# Generated by Django 5.2.9 on 2026-04-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('article_type', models.CharField(choices=[('guide', 'Guide'), ('service_explanation', 'Service explanation'), ('faq', 'FAQ'), ('update', 'Update'), ('promotion', 'Promotion')], default='guide', max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged in'), ('customer_only', 'Customer only'), ('admin_only', 'Admin only')], default='public', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('language', models.CharField(default='en', max_length=10)),
                ('show_on_blog', models.BooleanField(default=False)),
                ('show_in_help_center', models.BooleanField(default=False)),
                ('show_in_dashboard', models.BooleanField(default=False)),
                ('dashboard_card_title', models.CharField(blank=True, max_length=200)),
                ('dashboard_card_description', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.articlecategory')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['sort_order', '-published_at', '-created_at', 'title'],
            },
        ),
    ]
